### PR TITLE
normalize values to LC

### PR DESCRIPTION
**Pull request by jasondemorrow**

### CODE REVIEW

**Comment by jperasmus** [comment]
Hey Jason, thanks for the PR. Did you experience any cases where browsers provided any of these headers' values in non-lowercase values? I just realized now that I never added proper tests for this library so I won't ask for any tests 🤦‍♂️ - I'll add them in the coming days.

**Comment by jperasmus** [comment]
This is available in v0.3.1 now. I'll bump it to v1 once there is proper test coverage.

**Comment by jasondemorrow** [comment]
Thanks! To answer your question, I don't know that any browsers send non-LC, but I had a unit test of my own code (using your lib) that tried LC, UC, and sentence-case. This was what prompted me to add this. If and when you add some test scaffolding, I'll be happy to add a unit test for it here too.

**Comment by jperasmus** [comment]
Okay, excellent. Thanks for clarifying. I briefly scanned through the spec and MDN docs for these SecFetch headers and all of the examples always used lowercase values, but I did not see it explicitly called out that they had to be lowercase, so your fix helps in at least standardizing it for this middleware.

**Comment by jperasmus** [comment]
Took me a couple more days than I hoped to find time to add some tests, but they are added now and I've bumped the package to v1 in the process.

**Pull request merged**
